# Generated by Django 3.1.6 on 2021-02-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=32)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
